env:
  browser: true
  es2020: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: 
  react/react-in-jsx-scope: 'off'
  react/jsx-filename-extension: 'off'
  react/jsx-props-no-spreading: 'off'
  react/forbid-prop-types: 'off'
  react/jsx-closing-bracket-location: 'off'
  import/prefer-default-export: 'off'
  object-curly-newline: 'off'
  camelcase: 'off'
  no-continue: 'off'
  no-multiple-empty-lines: 
    - 2
    - max: 2
  jsx-a11y/anchor-is-valid: 
    - 'error'
    - components:
        - 'Link'
      specialLink:
        - 'hrefLeft'
        - 'hrefRight'
      aspects:
        - 'invalidHref'
        - 'preferButton'
globals:
  React: 'writable'
